// Inventar-Symbole normaler Rüstung, fein gezeichnet im 24er-Raster. Eine Form
// pro Namensform (gleiche Reihenfolge wie `nouns` in armorClasses.ts).
// Die Grundformen der schweren Rüstung dienen auch den Boss-Sets (bossArmor.ts).

import type { ArmorClass, ArmorSlot } from "../domain/types";
import { base, half, stamp } from "./pixelGrid";

export const BREASTPLATE = base([
  "",
  "",
  "....Lmmm",
  "..LLmmmmm",
  ".Lmmmmmmmm",
  ".Lmmmmmmmmmm",
  ".Lmmmmmmmmmm",
  "..Lmmmmmmmmm",
  "...Lmmmmmmmm",
  "...Lmmmmmmmm",
  "...Lmmmmmmmm",
  "...Lmmmmmmmm",
  "...Lmmmmmmmm",
  "...Lmmmmmmmm",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....tttttttt",
  "....Lmmmmmmm",
  "....DDDDDDDD",
]);

export const GAUNTLETS = base([
  "",
  "",
  "",
  "..tttttt",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..tttttt",
  "..LmmmmmD",
  ".LmmmmmmD",
  ".LmmmmmmD",
  ".LmmmmmmD",
  ".LmDmDmD",
  ".LmDmDmD",
  "..D.D.D",
]);

export const GREAVES = base([
  "",
  "",
  "...tttttt",
  "...LmmmmD",
  "...LmmmmD",
  "...tttttt",
  "...LmmmmD",
  "...LmmmmD",
  "...LmmmmD",
  "...LmmmmD",
  "...LmmmmD",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "....LmmmD",
  "....LmmmmD",
  "....DDDDDD",
]);

export const BOOTS = base([
  "",
  "",
  "",
  "",
  "",
  "....tttt",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "....LmmD",
  "...LmmmD",
  "..LmmmmD",
  ".LmmmmmD",
  ".DDDDDDD",
]);

/** Oberteil aus Stoff oder Leder mit kurzen Ärmeln (Gewand, Wams). */
const TUNIC = base([
  "",
  "",
  "...Lmm",
  "..Lmmmmm",
  ".Lmmmmmmmmmm",
  "Lmmmmmmmmmmm",
  "LmmLmmmmmmmm",
  "Lmm.Lmmmmmmm",
  "DDD.Lmmmmmmm",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....tttttttt",
  "....Lmmmmmmm",
  "....Lmmmmmmm",
  "....DDDDDDDD",
]);

/** Hose bzw. Beinkleid mit Bund, zwei Beine. */
const TROUSERS = base([
  "",
  "",
  "..tttttttttt",
  "..Lmmmmmmmmm",
  "..Lmmmmmmmmm",
  "..Lmmmmmmmmm",
  "..LmmmmmD",
  "..LmmmmmD",
  "..LmmmmmD",
  "..LmmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..LmmmmD",
  "..DDDDDD",
]);

/** Ein Arm mit diagonal gewickelten Binden (`t`), Zeile für Zeile versetzt. */
const WRAPS = Array.from({ length: 13 }, (_, i) => "...Lmmm".split("").map((ch, x) => (x === 3 + (i % 4) ? "t" : ch)).join("") + "D");

export const ARMOR_ICONS: Readonly<Record<ArmorClass, Readonly<Record<ArmorSlot, readonly (readonly string[])[]>>>> = {
  heavy: {
    head: [
      // Helm mit Federbusch, Sehschlitz und Luftlöchern
      base([
        "",
        "...........j",
        "..........jj",
        ".......Lmmmj",
        ".....LLmmmmm",
        "....Lmmmmmmm",
        "...Lmmmmmmmm",
        "...Lmmmmmmmm",
        "...ttttttttt",
        "...Lmmmmmmmm",
        "...Lmkkkkkkk",
        "...Lmmmmmmmm",
        "...Lmmkmmkmm",
        "...Lmmmmmmmm",
        "...Lmmkmmkmm",
        "....DDDDDDDD",
      ]),
      // Haube mit breiter Krempe (Eisenhut)
      base([
        "",
        "",
        "",
        "",
        ".........Lmm",
        ".......LLmmm",
        "......Lmmmmm",
        "......Lmmmmm",
        ".....Lmmmmjj",
        ".....ttttttt",
        ".LLmmmmmmmmm",
        "Lmmmmmmmmmmm",
        ".DDDDDDDDDDD",
      ]),
    ],
    chest: [
      // Harnisch
      stamp(BREASTPLATE, half(9, ["...........j"])),
      // Panzer: grosse Schulterplatten, gestaffelte Bauchschienen
      stamp(
        BREASTPLATE,
        half(1, [".LLmmD", "LmmmmmD", "LmmjmmD", ".DDDDD"]),
        half(9, ["...ddddddddd"]),
        half(12, ["...ddddddddd"]),
      ),
      // Brünne (Kettenhemd)
      base([
        "",
        "",
        "....LmLm",
        "..LmLmLmLm",
        ".LmLmLmLmLmL",
        "LmLmLmLmLmLm",
        "mLmLmLmLmLmL",
        "LmLmLmLmLmLm",
        "DD.LmLmLmLmL",
        "...mLmLmLmLm",
        "...LmLmLmLmL",
        "...mLmLmLmLm",
        "...LmLmLmLmL",
        "...mLmLmLmLm",
        "...ttttttttj",
        "...LmLmLmLmL",
        "...mLmLmLmLm",
        "...LmLmLmLmL",
        "...DDDDDDDDD",
      ]),
    ],
    arms: [
      // Armschienen
      base([
        "",
        "",
        "",
        "..tttttt",
        "..LmmmmD",
        "..LmmmmD",
        "..LmjjmD",
        "..LmmmmD",
        "..LmmmmD",
        "..tttttt",
        "..LmmmmD",
        "..LmmmmD",
        "..LmmmmD",
        "..LmmmmD",
        "..tttttt",
      ]),
      // Handschuhe
      GAUNTLETS,
      // Stulpen: weite Stulpe, darunter die Hand
      base([
        "",
        "",
        "LmmmmmmmmD",
        "tttttttttt",
        ".LmmmmmmD",
        ".LmmjjmmD",
        "..LmmmmD",
        "..LmmmmD",
        "..tttttt",
        "..LmmmmmD",
        ".LmmmmmmD",
        ".LmmmmmmD",
        ".LmDmDmD",
        ".LmDmDmD",
        "..D.D.D",
      ]),
    ],
    legs: [
      // Beinschienen
      stamp(GREAVES, half(3, ["....jj"])),
      // Beinlinge (Kettengeflecht)
      base([
        "",
        "",
        "..tttttttttt",
        "..LmLmLmLmLm",
        "..mLmLmLmLmL",
        "..LmLmLmLm",
        "..mLmLmLmL",
        "..LmLmLmL",
        "..mLmLmLm",
        "..LmLmLmL",
        "..mLmLmLm",
        "...LmLmL",
        "...mLmLm",
        "...LmLmL",
        "...mLmLm",
        "...ttttt",
        "...LmLmL",
        "...DDDDD",
      ]),
    ],
    feet: [
      // Stiefel
      BOOTS,
      // Schuhe
      base(["", "", "", "", "", "", "", "", "", "....tttt", "....LmmD", "....LmmD", "...LmmmD", "..LmmjmD", ".LmmmmmD", ".DDDDDDD"]),
    ],
  },

  light: {
    head: [
      // Kapuze
      base([
        "",
        "",
        "..........Lm",
        "........LLmm",
        ".......Lmmmm",
        "......Lmmmmm",
        ".....Lmmmkkk",
        ".....Lmmkkkk",
        "....Lmmkkkkk",
        "....Lmmkkkkk",
        "....Lmmkkkkk",
        "....Lmmmkkkk",
        "...Lmmmmmmkk",
        "..Lmmmmmmmmm",
        ".Lmmmmmmmmmm",
        ".ttttttttttj",
      ]),
      // Spitzhut
      base([
        "...........j",
        "...........L",
        "..........Lm",
        "..........Lm",
        ".........Lmm",
        ".........Lmm",
        "........Lmmm",
        "........Lmmm",
        ".......Lmmmm",
        ".......Lmmmm",
        "......Lmmmmm",
        "......tttttt",
        "......Lmmmmj",
        "LLmmmmmmmmmm",
        ".DDDDDDDDDDD",
      ]),
    ],
    chest: [
      // Robe: weit fallend, mit Schärpe und Saum
      base([
        "",
        "",
        "......Lmmm",
        "....LLmmmt",
        "..LLmmmmmmtj",
        ".Lmmmmmmmmmt",
        "Lmmmmmmmmmmt",
        "LmD.Lmmmmmmt",
        "Lm..Lmmmmmmt",
        "tt..Lmmmmmmt",
        "....Lmmmmmmt",
        "....tttttttt",
        "....Lmmmmmmt",
        "...Lmmmmmmmt",
        "...Lmmmmmmmt",
        "..Lmmmmmmmmt",
        "..Lmmmmmmmmt",
        ".Lmmmmmmmmmt",
        ".Lmmmmmmmmmt",
        ".ttttttttttt",
      ]),
      // Gewand: Kragen mit Edelstein, Gürtel
      stamp(TUNIC, half(2, ["......", ".........ttt", "..........tj"])),
    ],
    arms: [
      // Armbinden
      base(["", "", "", "...tttt", ...WRAPS, "...t.t"]),
      // Ärmel: gebauscht an der Schulter, Rüschen am Handgelenk
      base([
        "",
        "",
        "",
        "..LLmmD",
        ".LmmmmmD",
        ".LmmmmmD",
        ".LmmmmmD",
        "..LmmmD",
        "...LmmD",
        "...LmmD",
        "...LmmD",
        "...LmmD",
        "...LmmD",
        "..tttttt",
        "..t.t.t",
      ]),
    ],
    legs: [
      // Hose
      TROUSERS,
      // Beinkleider: weit, mit Edelstein am Bund, unten gerafft
      base([
        "",
        "",
        "..tttttttttt",
        ".Lmmmmmmmmtj",
        ".Lmmmmmmmmmm",
        ".Lmmmmmmmmm",
        ".LmmmmmmmD",
        ".LmmmmmmmD",
        ".LmmmmmmmD",
        ".LmmmmmmmD",
        ".LmmmmmmD",
        ".LmmmmmmD",
        ".LmmmmmmD",
        "..LmmmmD",
        "..tttttt",
        "...LmmD",
        "...DDDD",
      ]),
    ],
    feet: [
      // Sandalen
      base([
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "....t.t",
        "....t.t",
        "...t..t",
        "...tttt",
        "..t.t.t",
        ".tttttt",
        "Lmmmmmmm",
        "DDDDDDDD",
      ]),
      // Pantoffeln mit gebogener Spitze
      base(["", "", "", "", "", "", "", "", "t", "Lt", ".L...LmD", ".Lm.LmmD", ".LmmmmjmD", ".LmmmmmmD", ".DDDDDDDD"]),
    ],
  },

  medium: {
    head: [
      // Lederkappe mit Naht und Seitenlaschen
      base([
        "",
        "",
        "",
        "",
        "",
        ".........Lmm",
        ".......LLmmm",
        "......Lmmmmd",
        ".....Lmmmmmd",
        ".....Lmmmmmd",
        ".....Lmmmmmd",
        ".....tmtmmtm",
        ".....LmD",
        ".....LD",
      ]),
      // Haube mit Ohrenschutz
      base([
        "",
        "",
        "",
        "",
        ".........Lmm",
        ".......LLmmm",
        "......Lmmmmm",
        ".....Lmmmmmm",
        ".....Lmmmmjj",
        ".....ttttttt",
        ".....Lm",
        ".....Lm",
        "....LmmD",
        "....LmmD",
        "....DDD",
      ]),
    ],
    chest: [
      // Wams: gesteppt, Gürtelschnalle
      stamp(
        TUNIC,
        half(6, ["......d...d.", "............", "........d...", "............", "......d...d.", "............", "........d..."]),
        half(14, ["...........j"]),
      ),
      // Weste mit Schnürung
      base([
        "",
        "",
        "....Lm",
        "...Lmmm",
        "...Lmmmm",
        "...Lmmmmm",
        "...Lmmmmmm.t",
        "...Lmmmmmmk",
        "...Lmmmmmmmt",
        "...Lmmmmmmk",
        "...Lmmmmmmmt",
        "...Lmmmmmmk",
        "...Lmmmmmmmt",
        "...Lmmmmmmmm",
        "...tttttttt",
        "...Lmmmmmmmm",
        "...DDDDDDDDD",
      ]),
    ],
    arms: [
      // Lederhandschuhe: ohne Metallstulpe, mit Naht
      stamp(GAUNTLETS, half(3, ["..LmmmmD"]), half(9, ["..t.t.t."])),
      // Armschienen mit Riemen
      base([
        "",
        "",
        "",
        "..LmmmmD",
        "..LmmmmD",
        "..tttjtt",
        "..LmmmmD",
        "..LmmmmD",
        "..LmmmmD",
        "..tttjtt",
        "..LmmmmD",
        "..LmmmmD",
        "..LmmmmD",
        "..tttjtt",
        "..LmmmmD",
        "..DDDDDD",
      ]),
    ],
    legs: [
      // Lederhose mit Kniestück und Gürtelschnalle
      stamp(TROUSERS, half(2, ["...........j"]), half(9, ["...ttt"])),
      // Beinlinge mit Kniestück
      base([
        "",
        "",
        "..tttttttt",
        "...LmmmmD",
        "...LmmmmD",
        "...LmmmmD",
        "...LmmmmD",
        "..tttttttt",
        "..tLjmmmDt",
        "..tttttttt",
        "...LmmmmD",
        "...LmmmmD",
        "...LmmmmD",
        "...LmmmmD",
        "...LmmmmD",
        "...DDDDDD",
      ]),
    ],
    feet: [
      // Stiefel mit Umschlag
      stamp(BOOTS, half(4, ["...LmmmmD", "...tttttt"])),
      // Schnürschuhe
      base(["", "", "", "", "", "", "", "", "", "....LkmD", "....LmkD", "....LkmD", "...LmkmD", "..LmmmmD", ".LmmmmmD", ".DDDDDDD"]),
    ],
  },
};
