// Boss-Waffen in der Hand des Helden – im 24er-Raster des Helden, mit eigener
// Form pro Boss. Die Farben kommen aus der Boss-Palette (BOSS_LOOKS in
// itemSprites.ts), die Zeichen bedeuten dasselbe wie dort:
//   L/m/D  Material hell/mittel/dunkel   t  Zierde   j  Edelstein / Leuchten
//   h/H    Griff hell/dunkel             G  Griffstelle (2 × 2, hier liegt die Hand)
//   k/w    dunkle Details / Weiss (siehe SHARED_PALETTE)
// Schilde haben keine Griffstelle – sie werden mittig vor der Hand getragen.
//
// Grenzen im Heldenbild: höchstens 18 Zeilen über und 8 unter der Hand,
// höchstens 8 Spalten rechts neben der Hand.

export const BOSS_HELD: Readonly<Record<string, readonly string[]>> = {
  // --- Goblinhäuptling Krummzahn: grob, Knochen, grüne Lumpen ---------------
  "boss-goblin-chief-axe": [
    // Schartiges Hackbeil, mit grünen Lumpen gebunden
    "..tt......",
    "..hHLLLLL.",
    "..hHmmmmmL",
    "..ttmmjmmL",
    "..hHmmmmm.",
    "..ttmmmmmL",
    "..hHmDmDmL",
    "..hHDDDDD.",
    "..tt......",
    "..hH......",
    "..hH......",
    "..tt......",
    "..GG......",
    "..GG......",
    "..hH......",
    "..tt......",
    "..hH......",
    ".twwt.....",
  ],
  "boss-goblin-chief-mace": [
    // Knüppel mit eingeschlagenen Knochensplittern
    "....tt....",
    "..tLmmDt..",
    ".tLmmmmDt.",
    "..LmmmmmD.",
    "tLmmjjmmDt",
    "..LmmmmmD.",
    ".tLmmmmDt.",
    "..LmmmmD..",
    "...LmmD...",
    "...tLDt...",
    "....mD....",
    "....mD....",
    "....jj....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....jj....",
    "....hH....",
    "...tttt...",
  ],
  "boss-goblin-chief-bow": [
    // Knochenbogen mit Schädel als Griff
    ".wL.......",
    ".w.LL.....",
    ".w..Lm....",
    ".w..tm....",
    ".w...mmD..",
    ".w....tD..",
    ".w....mmD.",
    ".w....LmD.",
    ".w....www.",
    ".w....kwk.",
    "GG....www.",
    "GG....tjt.",
    ".w....LmD.",
    ".w....mmD.",
    ".w....tD..",
    ".w...mmD..",
    ".w..tm....",
    ".w..Lm....",
    ".w.LL.....",
    ".wL.......",
  ],

  // --- Uralte Sumpfechse: Zähne, Schuppen, gelbe Augen ----------------------
  "boss-ancient-lizard-sword": [
    // Ein riesiger gekrümmter Zahn als Klinge
    "....L...",
    "....LD..",
    "...LmD..",
    "...LmD..",
    "..LmmD..",
    "..LmmD..",
    "..LmmmD.",
    ".LmmmmD.",
    ".LmmmmD.",
    ".LmmmmD.",
    ".LmmmDD.",
    "tttjjttt",
    ".tttttt.",
    "..GG....",
    "..GG....",
    "..hH....",
    "..th....",
    "..hH....",
    "..tt....",
  ],
  "boss-ancient-lizard-greataxe": [
    // Sichelblatt mit Schuppen, mit Gold gefasst
    "....tt......",
    "....hH.LL...",
    "....hHLmmL..",
    "..t.hHmmDmL.",
    ".tL.hHmDmmmL",
    ".Lm.tjmmmDmL",
    ".Lm.tjmDmmmL",
    ".tL.hHmmmDmL",
    "..t.hHmDmmL.",
    "....hHLmmL..",
    "....hH.LL...",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....GG......",
    "....GG......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....tt......",
  ],
  "boss-ancient-lizard-dagger": [
    // Giftzahn, von dem Gift tropft
    "..w...",
    "..ww..",
    ".wwt..",
    ".wwt.j",
    ".wwtt.",
    "jwwtt.",
    "LmmmmD",
    ".LjjD.",
    "..GG..",
    "..GG..",
    "..mD..",
    "..mD..",
    ".LmmD.",
    "..mm..",
  ],

  // --- Das Höhlenauge: Kristall, ein starrendes Auge ------------------------
  "boss-cave-eye-staff": [
    // Ein Auge zwischen Kristallzacken
    "...t..t...",
    "..tL..Lt..",
    "..LwwwwD..",
    ".LwwjjwwD.",
    ".wwjkkjww.",
    ".wwjkkjww.",
    ".LwwjjwwD.",
    "..DwwwwD..",
    "..tLmmDt..",
    "...tmDt...",
    "....hH....",
    "....hH....",
    "...tttt...",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....tt....",
  ],
  "boss-cave-eye-sword": [
    // Prismaklinge: Kristall mit schillernden Facetten
    "....L...",
    "...LmD..",
    "..LtmmD.",
    "..LmtmD.",
    "..LmmtD.",
    "..LtmmD.",
    "..LmtmD.",
    "..LmmtD.",
    "..LtmmD.",
    "..LmtmD.",
    "..LmmtD.",
    "..LmmmD.",
    "ttwjjwtt",
    ".tttttt.",
    "...GG...",
    "...GG...",
    "...hH...",
    "...hH...",
    "..tmmt..",
    "...tt...",
  ],
  "boss-cave-eye-shield": [
    // Kristallspiegel mit dem Auge in der Mitte
    "...tttttt...",
    "..tLLmmmmt..",
    ".tLwwwwwwDt.",
    "tLwwwjjwwwDt",
    "tLwwjkkjwwDt",
    "tmwjkkkkjwDt",
    "tmwjkkkkjwDt",
    "tLwwjkkjwwDt",
    "tLwwwjjwwwDt",
    ".tLwwwwwwDt.",
    "..tDDDDDDt..",
    "...tttttt...",
  ],

  // --- Urmammut Graufrost: Elfenbein, Fell, Gletschereis --------------------
  "boss-primal-mammoth-greatsword": [
    // Ein Stosszahn als Klinge, nach vorn gebogen, mit Fell umwickelt
    "..........L.",
    ".........LD.",
    "........LmD.",
    ".......LmD..",
    "......LmmD..",
    ".....LmmD...",
    "....LmmD....",
    "...LmmmD....",
    "..LmmmD.....",
    "..LmmmmD....",
    "..LmmmmD....",
    ".tLmmmmDt...",
    "ttLmmmmDtt..",
    "..hhHHhh....",
    "..hHhHhH....",
    "...GG.......",
    "...GG.......",
    "...hH.......",
    "...hH.......",
    "...hH.......",
    "..tjjt......",
  ],
  "boss-primal-mammoth-greathammer": [
    // Ein Block Gletschereis mit Eiszapfen
    ".LLLLmmmmmD.",
    "LtmmmmmmmmmD",
    "LmmjmmmmjmmD",
    "LmmmmLmmmmmD",
    "LmmmmmmmmmmD",
    "DDmDDmmDDmDD",
    ".D.D.hH.D.D.",
    ".D...hH...D.",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....GG.....",
    ".....GG.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    "....tttt....",
  ],
  "boss-primal-mammoth-bow": [
    // Elfenbeinbogen mit Frostkristallen an den Enden, Fell am Griff
    "tw........",
    "tLL.......",
    ".wLm......",
    ".w.LmD....",
    ".w..LmD...",
    ".w...mD...",
    ".w....mD..",
    ".w....mD..",
    ".w....hH..",
    ".w....hHh.",
    "GG....hHh.",
    "GG....hH..",
    ".w....mD..",
    ".w....mD..",
    ".w...mD...",
    ".w..LmD...",
    ".w.LmD....",
    ".wLm......",
    "tLL.......",
    "tw........",
  ],

  // --- Der Lichkönig: dunkles Eisen, Knochen, grünes Seelenfeuer ------------
  "boss-lich-king-sword": [
    // Dunkle Klinge mit grün glühender Kante und Runen, Schädel als Parierstange
    "..tLLt..",
    "...LmL..",
    "..LmmmL.",
    "..LtmmL.",
    "..LmmtL.",
    "..LtmmL.",
    "..LmmmL.",
    "..LmtmL.",
    "..LtmmL.",
    "..LmmtL.",
    "..LmmmL.",
    "..LmmmL.",
    ".twwwwt.",
    "twkwwkwt",
    ".twwwwt.",
    "...GG...",
    "...GG...",
    "...hH...",
    "...hH...",
    "..tjjt..",
  ],
  "boss-lich-king-scepter": [
    // Schädel mit grün glühenden Augen und violetter Flamme
    "..t..t..",
    "...tt...",
    "..LLLD..",
    ".LmmmmD.",
    ".LjmmjD.",
    ".LmkkmD.",
    "..mmmD..",
    "..mwmw..",
    "...LD...",
    "..tmmt..",
    "...mD...",
    "...GG...",
    "...GG...",
    "...mD...",
    "...mD...",
    "..tLDt..",
    "...tt...",
  ],
  "boss-lich-king-greathammer": [
    // Ein Grabstein mit leuchtendem Kreuz, Totenkopf am Stiel
    "...LLLLLD...",
    "..LmmmmmmD..",
    ".LmmmmtmmmD.",
    ".LmmmtttmmD.",
    ".LmmmmtmmmD.",
    ".LmmmmtmmmD.",
    ".LmmmmmmmmD.",
    ".DDDDDDDDDD.",
    ".....hH.....",
    "....wwww....",
    "....kwwk....",
    ".....ww.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    ".....GG.....",
    ".....GG.....",
    ".....hH.....",
    ".....hH.....",
    ".....hH.....",
    "....tjjt....",
  ],

  // --- Ignaroth: Drachenrot, Gold, Glut --------------------------------------
  "boss-ignaroth-greatsword": [
    // Flammenklinge, gewellt wie eine Feuerzunge, Drachenflügel als Parierstange
    ".....j....",
    "....jL....",
    "....LmD...",
    "...LmmD...",
    "....LmmD..",
    "....LmmD..",
    "...LmmD...",
    "...LmmD...",
    "....LmmD..",
    "....LmmD..",
    "...LmmD...",
    "...LmmD...",
    "....LmD...",
    "ttttjjtttt",
    ".tt.tt.tt.",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "....hH....",
    "...tjjt...",
  ],
  "boss-ignaroth-greataxe": [
    // Drachenklaue mit drei Krallen
    "....tt..L...",
    "....hH.Lm...",
    "....hHLmD.L.",
    "....hHmD.Lm.",
    "....hHmmLmD.",
    "....tjmmmD.L",
    "....tjmmmmLm",
    "....hHmmmmmD",
    "....hHDmmmD.",
    "....hH.DDD..",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....GG......",
    "....GG......",
    "....hH......",
    "....hH......",
    "....hH......",
    "...tttt.....",
  ],
  "boss-ignaroth-mace": [
    // Glühender Morgenstern
    "....tt....",
    ".t..LD..t.",
    "..tLmmDt..",
    ".LmmjjmmD.",
    "tLmjLLjmDt",
    "tLmjLLjmDt",
    ".LmmjjmmD.",
    "..tDmmDt..",
    ".t..DD..t.",
    "....tt....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "...tjjt...",
  ],

  // --- Verlassene Mine: Eisen, Kupfer, Erz ----------------------------------
  "boss-ore-king-dagger": [
    // Grubendolch mit eingewachsener Erzader, Parierstange wie eine Spitzhacke
    "...L....",
    "...LD...",
    "..LmD...",
    "..LmmD..",
    "..LjmD..",
    "..LmjD..",
    "..LmmD..",
    "DmttttmD",
    ".DttttD.",
    "...GG...",
    "...GG...",
    "...hH...",
    "...tt...",
    "...hH...",
    "..tjjt..",
  ],
  "boss-ore-king-shield": [
    // Eisenplatte mit Gold- und Kupferadern
    "tttttttttttt",
    "tLLmmmmmmmDt",
    "tLmmjmmmmmDt",
    "tLmjjjmmtmDt",
    "tLmmjmmtttDt",
    "tLmmmmmmtmDt",
    "tLmtmmmmmmDt",
    "tLtttmmjmmDt",
    "tLmtmmjjjmDt",
    ".tLmmmmjmDt.",
    "..tDDDDDDt..",
    "...tttttt...",
  ],

  // --- Versunkener Tempel: Gold, Türkis, Lapislazuli ------------------------
  "boss-high-priestess-scepter": [
    // Sonnenscheibe mit Strahlen
    "....mm....",
    ".m.LmmD.m.",
    "..LjjjjD..",
    "mLjjjjjjDm",
    "mLjjjjjjDm",
    "..LjjjjD..",
    ".m.LmmD.m.",
    "....mm....",
    "...tmmt...",
    "....mD....",
    "...tttt...",
    "....mD....",
    "....GG....",
    "....GG....",
    "....mD....",
    "....mD....",
    "...tmmt...",
    "....tt....",
  ],
  "boss-high-priestess-mace": [
    // Skarabäus aus Türkis mit goldenen Beinen
    "...t..t...",
    "....LD....",
    "..tLmmDt..",
    ".t.tttt.t.",
    "..LmmmmD..",
    ".tLmjjmDt.",
    "..LmmmmD..",
    ".tLmmmmDt.",
    "..LmDLmD..",
    "...DmmD...",
    "....hH....",
    "....hH....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "...tjjt...",
  ],

  // --- Gewitterturm: Sturmblau, Blitzgelb -----------------------------------
  "boss-storm-lord-axe": [
    // Axtblatt mit einem Blitz darin
    "..tt......",
    "..hH.LL...",
    "..hHLmmL..",
    "..hHmmtmL.",
    "..ttmtmmmL",
    "..ttmmtmmL",
    "..hHmtmmmL",
    "..hHmmtmL.",
    "..hHLmmL..",
    "..hH.LL...",
    "..hH......",
    "..hH......",
    "..hH......",
    "..hH......",
    "..GG......",
    "..GG......",
    "..hH......",
    "..hH......",
    "..tt......",
  ],
  "boss-storm-lord-staff": [
    // Blitzzacken um eine Sturmkugel
    ".m......m.",
    ".mm....mm.",
    "..m.jj.m..",
    "..mjjjjm..",
    "..tjLLjt..",
    "..tjjjjt..",
    "...tjjt...",
    "....hH....",
    "....hH....",
    "....hH....",
    "..m.hH.m..",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "....hH....",
    "...tttt...",
  ],

  // --- Abgrund der Leere: Schwarzviolett, türkises Leuchten -----------------
  "boss-void-lord-dagger": [
    // Ein zackiger Splitter aus Leere
    "....t...",
    "...tL...",
    "...Lmt..",
    "..tmmD..",
    "..LmmDt.",
    ".tmmmD..",
    "..LmmmDt",
    ".tLmmD..",
    "tt.jj.tt",
    ".t.tt.t.",
    "...GG...",
    "...GG...",
    "...mD...",
    "...mD...",
    "...tt...",
  ],
  "boss-void-lord-shield": [
    // Ein Strudel in der Mitte, Zacken am Rand
    "t..tttttt..t",
    ".tLmmmmmmDt.",
    "tLmmmmmmmmDt",
    "tLmmttttmmDt",
    "tLmtmmmmtmDt",
    "tLmtmjjmtmDt",
    "tLmtmjkjtmDt",
    "tLmmtttmtmDt",
    "tLmmmmmtmmDt",
    ".tLmmmmmmDt.",
    "t.tDDDDDDt.t",
    "....tttt....",
  ],

  // --- Sumpfhydra: Schuppengrün, Giftzähne ----------------------------------
  "boss-swamp-hydra-scepter": [
    // Drei Schlangenköpfe
    "Lm..Lm..Lm",
    "jm..jm..jm",
    "mw..mw..mw",
    "mD..mD..mD",
    ".mD.mD.mD.",
    "..mDmDmD..",
    "...mmmD...",
    "...tjjt...",
    "....mD....",
    "....mD....",
    "....GG....",
    "....GG....",
    "....mD....",
    "....mD....",
    "...tttt...",
    "....tt....",
  ],
  "boss-swamp-hydra-axe": [
    // Schlangenkopf mit offenem Maul als Axtblatt
    "..tt......",
    "..hHLmm...",
    "..hHmmjmL.",
    "..hHmmmmmL",
    "..ttmmw.w.",
    "..hHmm....",
    "..ttmmw.w.",
    "..hHmmmmmL",
    "..hHDmmmD.",
    "..hH......",
    "..hH......",
    "..hH......",
    "..hH......",
    "..hH......",
    "..GG......",
    "..GG......",
    "..hH......",
    "..hH......",
    "..tt......",
  ],

  // --- Frostriese: Gletschereis, Eiszapfen ----------------------------------
  "boss-frost-giant-greataxe": [
    // Zackige Eisaxt
    "....jj......",
    "....hH..L...",
    "....hH.LmL..",
    "..L.hHLmmmL.",
    ".Lm.hHmmjmmL",
    "LmD.tjmmmmmD",
    "LmD.tjmmjmmD",
    ".Lm.hHmmmmD.",
    "..L.hHDmmD..",
    "....hH.DmD..",
    "....hH..D...",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....GG......",
    "....GG......",
    "....hH......",
    "....hH......",
    "....hH......",
    "....jj......",
  ],
  "boss-frost-giant-bow": [
    // Bogen aus Eiszapfen
    ".wL.......",
    ".w.Lj.....",
    ".w.LmD....",
    ".w..LmDj..",
    ".w...mD...",
    ".w...LmDj.",
    ".w....mD..",
    ".w....mDj.",
    ".w....hH..",
    ".w....jj..",
    "GG....hH..",
    "GG....mD..",
    ".w....mDj.",
    ".w...LmD..",
    ".w...mDj..",
    ".w..LmD...",
    ".w.LmDj...",
    ".w.Lj.....",
    ".wL.......",
  ],

  // --- Weltenverschlinger: Leerenviolett, Gold, roter Schlund ---------------
  "boss-world-eater-greatsword": [
    // Gezahnte Klinge mit rotem Auge, Parierstange wie ein Maul
    "....L.....",
    "....LD....",
    "...LmmDw..",
    "...LmmD...",
    "...LmkDw..",
    "...LmkD...",
    "...LmkDw..",
    "...LmkD...",
    "...LmkDw..",
    "...LmmD...",
    "...LjjDw..",
    "...LmmD...",
    "ttwwjjwwtt",
    ".ttkkkktt.",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "....hH....",
    "...tjjt...",
  ],
  "boss-world-eater-staff": [
    // Ein aufgerissenes Maul mit rotem Schlund
    "..t....t..",
    ".tLm..mDt.",
    ".Lw....wD.",
    "Lmw.jj.wmD",
    "Lm.jkkj.mD",
    "Lmw.jj.wmD",
    ".Lw....wD.",
    ".tLmwwmDt.",
    "..tLmmDt..",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....hH....",
    "....GG....",
    "....GG....",
    "....hH....",
    "....hH....",
    "....hH....",
    "...tjjt...",
  ],
};
